#+TITLE: Project structure test

Quite often, I'm sharing my =OCaml= work as standard shared objects (aka =.so= or
=.dll=). I recently manage to compile such a project with =dune=.

A ~shared_object~ linking mode was recently added to [[https://github.com/ocaml/dune][dune]]. I tried to take
advantage of it to simplify my =jbuild= files. Without success.

I'm creating the current project, in order to understand how to set things (and
get help on a concrete project).

*Thanks to @diml who pointed my mistakes, this now works!*

Tests were performed with development version of =jbuilder=:
: $ jbuilder --version
: 1.0+beta19-33-g73231bf

The =lib/= directory is there to provide a two functions pure =OCaml= lib:
=mylib=, which is to be shared to =C= users (I'll jump later to a more complex
OCaml library that will have to be linked to third parties C lib).

#+NAME: mylib.mli
#+BEGIN_SRC ocaml
val add: int -> int -> int
val substract: int -> int -> int
#+END_SRC

The =manual/= directory contains my current working project, which I'd like to
simplify, while the =automatic= will eventually host the improved solution.

* Makefile targets

  * clean
  * manualtest: builds a shared DLL the complicated way and run a small C test program on it
  * directdll: just build a shared DLL
  * directtest: run a small C test program on the directdll

* manual/

** dll/

   This directory builds =myclib.so= from:

   * =myclib.h=
   * =mylib_stub.c=: the =C= part of the shared library
   * =mylib_mlstub.ml=: the =OCaml= part of the library (registering functions
     from  =mylib=)

** test/

   This directory contains a C test file.

   To test, just do ~make manualtest~:
   #+BEGIN_SRC bash
   $ make manualtest
   jbuilder build @runmanualtest
        montest alias manual/test/runmanualtest
   Avant init : 0
   Après init : 1
   Somme : 5 + 7 = 12
   Soustraction : 5 - 7 = -2
   #+END_SRC

* automatic/

  This directory is a +*failing*+ *working* attempt to build another version: ~direct.so~.

  It builds with:
  : make directdll

** test/

   This directory contains a C test file.

   To test, just do ~make directtest~:
