#+TITLE: Project structure test

Quite often, I'm sharing my =OCaml= work as standard shared objects (aka =.so= or
=.dll=). I recently manage to compile such a project with =dune=.

A ~shared_object~ linking mode was recently added to [[https://github.com/ocaml/dune][dune]]. I tried to take
advantage of it to simplify my =jbuild= files. Without success.

I'm creating the current project, in order to understand how to set things (and
get help on a concrete project).

Tests were performed with development version of =jbuilder=:
: $ jbuilder --version
: 1.0+beta19-33-g73231bf

The =lib/= directory is there to provide a two functions pure =OCaml= lib:
=mylib=, which is to be shared to =C= users (I'll jump later to a more complex
OCaml library that will have to be linked to third parties C lib).

#+NAME: mylib.mli
#+BEGIN_SRC ocaml
val add: int -> int -> int
val substract: int -> int -> int
#+END_SRC

The =manual/= directory contains my current working project, which I'd like to
simplify, while the =automatic= will eventually host the improved solution.

* manual/

** dll/

   This directory builds =myclib.so= from:

   * =myclib.h=
   * =mylib_stub.c=: the =C= part of the shared library
   * =mylib_mlstub.ml=: the =OCaml= part of the library (registering functions
     from  =mylib=)

** test/

   This directory contains a C test file.

   To test, just do ~make manualtest~:
   #+BEGIN_SRC bash
   $ make manualtest
   jbuilder build @runmanualtest
        montest alias manual/test/runmanualtest
   Avant init : 0
   Après init : 1
   Somme : 5 + 7 = 12
   Soustraction : 5 - 7 = -2
   #+END_SRC

* automatic/

  This directory is a *failing* attempt to build another version: ~direct.so~.

  It builds with:
  : make directdll

  But it is not the library I would expect (I can't find the expected symbols in
  it):

  #+BEGIN_SRC bash
  $ objdump -t _build/default/manual/dll/myclib.so | grep mylib
  0000000000000000 l    df *ABS*	0000000000000000              mylib_stub.c
  0000000000260358 l     O .bss	0000000000000004              mylib_init_done
  0000000000031050 g     F .text	0000000000000030              init_mylib
  $ objdump -t _build/default/automatic/dll/direct.so | grep mylib
  #+END_SRC

** test/

   This directory contains a C test file.

   To test, just do ~make directtest~:
   #+BEGIN_SRC bash
$ make directtest
jbuilder build @runautomatictest
         gcc automatic/test/direct.so,automatic/test/montest.exe,automatic/test/myclib.h (exit 1)
(cd _build/default/automatic/test && /usr/bin/gcc -O2 -fno-strict-aliasing -fwrapv -fPIC -o montest.exe -Wl,-rpath,. direct.so test.c)
/tmp/cclBM5MH.o : Dans la fonction « main » :
test.c:(.text.startup+0x4) : référence indéfinie vers « init_done »
test.c:(.text.startup+0x2a) : référence indéfinie vers « init_mylib »
test.c:(.text.startup+0x31) : référence indéfinie vers « init_done »
test.c:(.text.startup+0x58) : référence indéfinie vers « do_add »
test.c:(.text.startup+0x7f) : référence indéfinie vers « do_substract »
collect2: error: ld returned 1 exit status
Makefile:7 : la recette pour la cible « directtest » a échouée
make: *** [directtest] Erreur 1
   #+END_SRC
